// Auto-generated by scripts/build_template_registry.py
// 22 templates from 3_Template_Prompts/
// Do not edit by hand — re-run the script after adding templates

const TEMPLATES = {
  "gao_yuan_yuan": {
    id: "gao_yuan_yuan",
    name: `高圆圆·艺术极简气质写真 - 完整场景分析与提示词`,
    styleName: `高圆圆·艺术极简气质写真 - 完整场景分析与提示词`,
    category: `高圆圆·艺术写真`,
    description: `高圆圆·艺术极简气质写真 - 完整场景分析与提示词`,
    format: "raw",
    tags: [],
    shots: {
      "1": `# 高圆圆·艺术极简气质写真 - 完整场景分析与提示词

## 基本信息

**照片风格**：艺术极简气质写真  
**核心定位**：当代艺术感 + 极简主义 + 知性气质  
**适用场景**：艺术写真、杂志内页、个人品牌照、艺术展览  
**目标人群**：气质型女性、职场精英、艺术爱好者、文艺青年

---

## 第一维度：人物气质与妆造分析

### 肤色特征
- **色调**：冷色调，偏白皙
- **透亮度**：高透亮感，显肌肤质感细腻
- **质感**：哑光质地，显成熟感，无油光
- **评价**：典型的"高级肤色"，冷色调搭配哑光质感显得知性而不失温度

### 眼妆特点
- **眼影**：极简设计，几乎无色或浅棕色，强调眼部立体感
- **眼线**：细致眼线，内眼线强调，显眼睛深邃
- **睫毛**：自然卷翘，根根分明，显眼睛神韵
- **眼神**：向下看，温柔内敛，显思考感和气质
- **评价**：这是"艺术写真级别"的眼妆，不追求浓妆艳抹，而是强调眼睛的神韵和气质

### 唇妆特点
- **颜色**：低饱和度红棕色，显气质不显廉价
- **质地**：哑光质地，显成熟感
- **饱和度**：低饱和，显高级感
- **评价**：唇妆是整个妆容的点睛之笔，低饱和度红棕色既显气质又不抢镜

### 发型特征
- **长度**：齐肩短发，显脸小显气质
- **卷度**：微卷，蓬松感适中
- **发色**：深棕色/黑色，显肤色白皙
- **发质感**：有光泽感，显健康感
- **发型风格**：现代剪裁，显知性感
- **评价**：短发设计是这张照片的灵魂，齐肩长度配合微卷显得既年轻又成熟

### 整体气质总结
- **主要气质**：知性、内敛、艺术感、温柔
- **次要气质**：极简、高级、思考感、文艺
- **气质等级**：高级感，适合高端品牌代言
- **气质评价**：这是典型的"当代艺术女性"气质，既有知识分子的内敛，又有艺术家的灵气

---

## 第二维度：服饰搭配分析

### 服装类型
- **主体**：白色宽松衬衫/衬衣
- **版型**：宽松廓形，肩部设计宽松
- **材质**：棉麻混纺或纯棉，有质感和垂坠感
- **设计细节**：露肩设计，显锁骨和颈部线条

### 颜色搭配
- **主色**：白色，显肤色白皙，显清爽感
- **辅色**：黑色（下装），形成黑白对比
- **搭配逻辑**：白色上衣 + 黑色下装 = 极简黑白配 = 高级感
- **色彩心理**：白色代表纯净、艺术；黑色代表深度、知性

### 面料质感
- **上衣面料**：棉麻混纺，有自然褶皱感，显质感
- **下装面料**：黑色棉质或混纺，显垂坠感
- **整体质感**：自然、舒适、有质感，不显廉价

### 版型特点
- **上衣版型**：宽松廓形，不贴身，显身材又显气质
- **肩部设计**：宽松肩，显肩宽，显气场
- **露肩设计**：露肩部分，显锁骨和颈部线条，显女性感
- **下装版型**：紧身或直筒，与上衣宽松形成对比

### 配饰搭配
- **项链**：细金色项链，简约设计，显气质
- **戒指**：细戒指，显手部线条
- **整体配饰**：极简主义，不追求繁复，强调质感

### 服饰搭配逻辑总结
- **核心逻辑**：极简黑白配 + 宽松廓形 + 细致配饰 = 当代艺术感
- **风格定位**：极简主义、当代艺术、高级感
- **适用场景**：艺术展览、高端品牌、杂志拍摄、个人品牌照
- **搭配评价**：这是"设计师级别"的搭配，每一个细节都经过精心考虑

---

## 第三维度：光影设计分析

### 光线方向
- **主光方向**：侧光，从左上方 45-60 度角照射
- **光线特点**：侧光强调了人物的立体感和轮廓
- **阴影方向**：人物右侧有明显阴影，增加深度感

### 光线强度
- **光线强度**：中等强度柔光
- **光线质感**：柔和不刺眼，显温柔感
- **光线均匀度**：光线分布均匀，显专业感

### 光线质感
- **光线类型**：自然光或模拟自然光
- **光线特点**：带有漫射效果，显柔和感
- **光线质感**：温暖而不过曝，冷调而不过冷

### 阴影处理
- **阴影深度**：浅阴影，面部有轻微的阴影勾勒
- **阴影位置**：右侧脸部和颈部有阴影
- **阴影作用**：增加立体感，显脸型立体

### 色温
- **色温特征**：中性偏暖，整体显温暖感
- **色温效果**：显肤色温暖，显气质温柔
- **色温评价**：这是"高级色温"，既不过冷显生硬，也不过暖显廉价

### 特殊效果
- **胶片感**：有轻微的胶片颗粒感，显复古艺术感
- **漏光效果**：背景有轻微的漏光效果，增加艺术感
- **整体效果**：显复古、显艺术、显高级

### 光影设计总结
- **光影等级**：专业级别，体现了摄影师的专业水准
- **光影特点**：侧光 + 柔光 + 中性色温 + 胶片感 = 艺术写真级别
- **光影评价**：这是典型的"艺术写真光影"，每一束光都经过精心设计

---

## 第四维度：镜头语言分析

### 焦段
- **焦段选择**：85mm 定焦镜头（推测）
- **焦段特点**：85mm 是人像摄影的黄金焦段
- **焦段效果**：显脸型立体，显人物气质

### 光圈
- **光圈大小**：f/1.4 - f/1.8（推测）
- **光圈效果**：背景虚化强烈，显人物突出
- **景深效果**：极浅景深，只有人物清晰，背景完全虚化

### 景别
- **景别类型**：半身特写
- **景别范围**：从腰部以上到头部
- **景别特点**：既能展现人物气质，又能展现服饰搭配

### 拍摄角度
- **拍摄角度**：平视或略微俯视
- **角度特点**：与人物视线平行或略低
- **角度效果**：显人物气质，不显压抑

### 构图方式
- **构图方法**：中心构图 + 三分法混合
- **人物位置**：人物居中偏左
- **构图特点**：人物占据画面 60-70%，留白适当
- **构图评价**：这是"艺术写真级别"的构图，既不过满也不过空

### 镜头语言总结
- **镜头等级**：专业级别
- **镜头特点**：85mm f/1.4 + 平视 + 中心构图 = 专业人像摄影
- **镜头评价**：每一个镜头参数都经过精心选择，体现了摄影师的专业水准

---

## 第五维度：背景环境分析

### 背景类型
- **背景类型**：室内背景，艺术装置背景
- **背景特点**：背景中有艺术装置（上半部分的白色抽象形状）

### 背景颜色
- **主色**：深灰色/深棕色，显沉静感
- **辅色**：白色（艺术装置），形成对比
- **背景色彩**：低饱和度，显高级感

### 背景质感
- **背景虚化**：完全虚化，显专业感
- **背景纹理**：无明显纹理，显简洁感
- **背景质感**：柔和虚化，显艺术感

### 背景故事感
- **背景故事**：艺术装置背景，暗示艺术展览或美术馆
- **故事感强度**：中等，既不过于明显也不过于隐晦
- **故事感评价**：背景完美诠释了"艺术气质"这一主题

### 背景与人物的关系
- **关系类型**：融合关系，背景与人物相互呼应
- **关系特点**：背景的艺术装置与人物的艺术气质相互呼应
- **关系评价**：背景不是陪衬，而是与人物一起讲述"艺术"这个故事

### 背景环境总结
- **背景等级**：高级背景，体现了场景选择的用心
- **背景特点**：艺术装置 + 深色背景 + 完全虚化 = 艺术写真级别
- **背景评价**：这是"美术馆级别"的背景，完美诠释了整个照片的艺术主题

---

## 第六维度：整体氛围与情绪分析

### 主要情绪
- **情绪 1**：知性、内敛
- **情绪 2**：思考、沉思
- **情绪 3**：温柔、优雅
- **情绪 4**：艺术、文艺
- **情绪总结**：这是一种"知性温柔的艺术气质"

### 风格定位
- **风格**：当代艺术 + 极简主义 + 高级感
- **风格特点**：既有艺术展览的高级感，又有日常生活的温柔感
- **风格评价**：这是"当代艺术女性"的典型风格

### 色调氛围
- **色调**：冷色调中带有暖色调，形成平衡
- **氛围**：沉静、高级、艺术
- **色调评价**：色调搭配完美，既不过冷显生硬，也不过暖显廉价

### 整体质感
- **质感 1**：高级感，体现在妆造、服饰、光影的每一个细节
- **质感 2**：艺术感，体现在背景、构图、整体氛围
- **质感 3**：温柔感，体现在眼神、光影、色调
- **质感总结**：这是"高级艺术感"与"温柔气质"的完美结合

### 视觉层级
- **第一层**：人物面部和眼神（最清晰，最吸引注意力）
- **第二层**：人物身体和服饰（清晰，展现搭配）
- **第三层**：背景艺术装置（虚化，提供氛围）
- **第四层**：背景色彩（完全虚化，提供色彩基调）
- **层级评价**：视觉层级清晰，引导观看者的视线流动

### 整体氛围总结
- **氛围等级**：高级艺术写真级别
- **氛围特点**：知性 + 温柔 + 艺术 + 极简 = 当代艺术女性
- **氛围评价**：这张照片成功地传达了"一个有品味、有气质、有思想的女性"这一人物设定

---

## 第七维度：风格共性提炼

### 核心美学特征

**当代艺术极简风 + 知性温柔气质 + 高级感**

这张照片的核心美学特征可以用一句话总结：**"用极简的语言讲述艺术的故事，用温柔的气质诠释知性的力量"**

### 关键要素（5 大支柱）

#### 要素 1：极简黑白配
- 白色宽松衬衫 + 黑色下装 = 黑白对比
- 极简配饰 + 细致妆造 = 克制而精致
- 作用：奠定整个照片的"极简"基调

#### 要素 2：艺术背景与装置
- 艺术装置背景 = 艺术展览感
- 深色虚化背景 = 高级感
- 作用：强化"艺术"这一核心主题

#### 要素 3：侧光 + 胶片感
- 侧光强调立体感 = 显气质
- 胶片颗粒感 = 显艺术感、复古感
- 作用：提升整个照片的"艺术质感"

#### 要素 4：知性内敛的眼神
- 向下看的眼神 = 思考感、内敛感
- 细致的眼妆 = 显气质不显浓妆
- 作用：传达"有思想、有品味"的人物设定

#### 要素 5：齐肩短发 + 低饱和度妆造
- 齐肩短发 = 显气质、显知性
- 低饱和度妆造 = 显高级感、显成熟感
- 作用：强化"当代艺术女性"的人物设定

### 适用人群

**一级适用人群**：
- 气质型女性
- 职场精英女性
- 艺术爱好者
- 文艺青年
- 有品味的女性

**二级适用人群**：
- 高端品牌代言人
- 杂志编辑/记者
- 美术馆/画廊工作人员
- 设计师/创意工作者
- 知识工作者

**三级适用人群**：
- 30+ 成熟女性
- 有一定社会地位的女性
- 追求品质生活的女性

### 变化空间

**可以改变的维度**：
1. **服装颜色**：可以改为其他极简色系（米色、灰色、深蓝色），但要保持极简风格
2. **背景**：可以改为其他艺术背景（美术馆、画廊、建筑空间），但要保持高级感
3. **妆造**：可以改为其他低饱和度色系，但要保持知性气质
4. **发型**：可以改为其他短发或长发，但要保持气质感

**不能改变的维度**：
1. **极简黑白配**的基调（这是核心）
2. **知性内敛**的气质（这是灵魂）
3. **艺术感**的氛围（这是主题）
4. **高级感**的质感（这是品质）

### 风格共性总结

**一句话定义**：当代艺术极简风 = 黑白配 + 艺术背景 + 知性气质 + 高级感

**核心价值**：这个风格适合那些"有品味、有思想、有气质"的女性，用极简的视觉语言传达深层的艺术内涵。

**市场定位**：高端品牌、艺术展览、杂志拍摄、个人品牌照

**竞争优势**：在众多"甜美风""性感风"的写真中，这种"艺术极简风"显得独特而高级，更容易吸引高端客户。

---

## 生成的 8 组镜头提示词

### 提示词组 1：经典艺术极简风（参考原图）

\`\`\`
A sophisticated Asian woman with short shoulder-length dark hair, 
wearing a white oversized linen shirt and black pants, 
standing in an art gallery with abstract white sculpture in the background.
Soft side lighting from the left, creating subtle shadows on the right side of her face.
Neutral color palette with black, white, and warm skin tones.
Professional portrait photography, 85mm lens, f/1.4 aperture,
shallow depth of field with blurred background.
Film grain effect, artistic and minimalist aesthetic.
Looking down thoughtfully, serene and contemplative expression.
High-end fashion magazine editorial style.
\`\`\`

### 提示词组 2：特写艺术气质版

\`\`\`
Close-up portrait of an elegant Asian woman with short dark hair,
minimal makeup with muted red-brown lipstick, 
wearing a white oversized shirt with shoulder cutout.
Soft directional lighting emphasizing facial contours and bone structure.
Neutral background, completely blurred, deep gray tone.
Film photography aesthetic with subtle grain.
Thoughtful expression, eyes looking downward.
Professional beauty and fashion photography.
High-end luxury brand aesthetic.
\`\`\`

### 提示词组 3：全身艺术装置背景版

\`\`\`
Full-body shot of an Asian woman with short dark hair,
wearing a white oversized linen shirt and black trousers,
standing in front of a modern art installation with white abstract forms.
Natural side lighting creating dramatic shadows.
Minimalist composition, centered framing.
Warm neutral color grading with film grain.
Serene and artistic atmosphere.
Contemporary art gallery setting.
High fashion editorial photography.
\`\`\`

### 提示词组 4：细节配饰展示版

\`\`\`
Medium shot of an elegant woman with short dark hair,
wearing a white oversized shirt with delicate gold chain necklace and fine ring.
Soft lighting highlighting skin texture and jewelry details.
Neutral minimalist background.
Hands visible holding a small object or book.
Thoughtful, introspective mood.
Luxury lifestyle photography.
Contemporary minimalist aesthetic.
\`\`\`

### 提示词组 5：侧面轮廓版

\`\`\`
Side profile of an Asian woman with short dark hair,
wearing a white oversized linen shirt.
Dramatic side lighting creating strong contours and shadows.
Artistic background with abstract elements.
Film photography aesthetic.
Contemplative and serene expression.
Professional portrait photography.
Minimalist composition.
High-end editorial style.
\`\`\`

### 提示词组 6：低角度仰视版

\`\`\`
Low angle shot of a woman with short dark hair,
wearing a white oversized shirt, looking down.
Soft overhead lighting creating gentle shadows.
Neutral background, completely blurred.
Emphasizing the elegance of neck and shoulders.
Artistic and minimalist aesthetic.
Film grain effect.
Professional beauty photography.
Luxury brand aesthetic.
\`\`\`

### 提示词组 7：环境融合版

\`\`\`
Woman in a modern art gallery space,
wearing white oversized linen shirt and black pants,
with contemporary art installation visible in background.
Natural window lighting creating soft directional shadows.
Minimalist color palette.
Thoughtful, artistic atmosphere.
Editorial fashion photography.
Professional gallery portrait.
High-end lifestyle aesthetic.
\`\`\`

### 提示词组 8：极简黑白版

\`\`\`
Black and white portrait of an Asian woman with short dark hair,
wearing an oversized white shirt.
Soft side lighting creating dramatic tonal contrast.
Minimalist composition with negative space.
Fine art photography aesthetic.
Contemplative expression.
Professional portrait photography.
Artistic and timeless quality.
High-end editorial style.
\`\`\`

---

## 提示词使用指南

### 如何使用这些提示词

1. **选择合适的提示词组**
   - 如果想要经典风格，使用「提示词组 1」
   - 如果想要特写人物，使用「提示词组 2」
   - 如果想要展示全身，使用「提示词组 3」

2. **根据需要调整参数**
   - 改变服装颜色：将"white oversized shirt"改为"beige oversized shirt"
   - 改变背景：将"art gallery"改为"minimalist studio"
   - 改变表情：将"looking down"改为"looking at camera"

3. **输入到 AI 生图工具**
   - 豆包 AI 绘画
   - 即梦 AI
   - Midjourney
   - DALL-E 3

4. **优化生成结果**
   - 如果生成的图片过于相似，可以调整"lighting"或"angle"参数
   - 如果想要更多变化，可以组合不同提示词组的元素

### 提示词优化建议

**如果想要更高级的效果**：
- 添加"shot by a renowned fashion photographer"
- 添加"Vogue editorial style"
- 添加"professional color grading"

**如果想要更艺术的效果**：
- 添加"fine art photography"
- 添加"gallery exhibition quality"
- 添加"contemporary art aesthetic"

**如果想要更温柔的效果**：
- 改变"dramatic"为"soft"
- 改变"strong contours"为"gentle contours"
- 添加"warm and inviting atmosphere"

---

## 核心总结

### 这张照片为什么成功

1. **视觉统一**：黑白配 + 极简风格 + 艺术背景 = 完整的视觉语言
2. **气质传达**：知性 + 温柔 + 艺术 = 清晰的人物设定
3. **专业水准**：光影 + 构图 + 妆造 + 服饰 = 每一个细节都经过精心设计
4. **市场价值**：高端品牌 + 艺术展览 + 杂志拍摄 = 清晰的商业定位

### 如何复制这个风格

1. **妆造**：低饱和度、哑光质地、强调气质而非浓妆
2. **服饰**：极简黑白配、宽松廓形、细致配饰
3. **光影**：侧光 + 柔光 + 中性色温 + 胶片感
4. **背景**：艺术感 + 高级感 + 虚化处理
5. **气质**：知性 + 内敛 + 思考感 + 温柔

### 适用场景

- ✅ 高端品牌代言
- ✅ 杂志编辑内页
- ✅ 艺术展览宣传
- ✅ 个人品牌照
- ✅ 职场女性形象照
- ✅ 艺术机构宣传
- ✅ 高端服装品牌
- ✅ 美术馆/画廊宣传

---

## 文件信息

**分析照片**：XPzDsAugDnnh.webp  
**风格名称**：高圆圆·艺术极简气质写真  
**分析框架**：7 维度完整分析  
**生成提示词**：8 组专业级提示词  
**分析时间**：2026-05-23  
**适用工具**：豆包 AI、即梦 AI、Midjourney、DALL-E 3

---

## 下一步建议

1. **快速验证**：选择「提示词组 1」，输入到 AI 生图工具，验证效果
2. **风格迭代**：根据生成结果，调整提示词中的关键参数
3. **批量生成**：使用其他 7 组提示词，生成不同风格的变体
4. **库存积累**：重复这个过程，分析其他 22 张高圆圆照片，积累 176 套提示词
5. **商业变现**：将这些提示词打包成"高圆圆风格提示词库"，在小红书/知识星球售卖

---

**本文档已完成，可直接用于 AI 写真生成和商业变现。**`
    },
    commonBase: "",
    negativeConstraints: `deformed face, plastic skin, over-smoothed, different person, blurry, watermark, signature`
  },
  "mini_me": {
    id: "mini_me",
    name: `Mini Me · 迷你分身创意写真`,
    styleName: `Mini Me · 迷你分身创意写真`,
    category: `创意·Mini Me`,
    description: `将照片变成迷你分身的创意世界，3D风格小角色在身边互动玩耍`,
    format: "raw",
    tags: [],
    shots: {
      "1": `Turn this photo into a magical “Mini Me” world where tiny animated versions of yourself come to life around you. These cute 3D-style mini characters interact with your everyday surroundings — climbing onto your shoulders, sitting on your bag, waving, playing, and copying your poses — creating a playful yet emotional social media story-worthy scene full of personality and story. The original photo remains untouched while the tiny characters bring the image to life with depth, movement, realistic shadows, and a soft aesthetic vibe.`
    },
    commonBase: "",
    negativeConstraints: `deformed face, plastic skin, over-smoothed, different person, blurry, watermark, signature`
  },
  "zhang_man_yu_01": {
    id: "zhang_man_yu_01",
    name: `戛纳影后·盛装礼服风`,
    styleName: `戛纳影后·华丽礼服·高光时刻`,
    category: `张曼玉·红毯与礼服`,
    description: `欧洲顶级电影节红毯·高定礼服大片`,
    format: "zm_v1",
    tags: [`冷艳高贵`, `成熟自信`, `国际大牌气场`],
    shots: {
      "1": `Elegant Asian woman in a sleek black high-fashion gown, full body shot showing complete dress silhouette, professional red carpet lighting, even bright illumination, standing confidently with slight body angle, luxurious jewelry catching light, 85mm lens, f/2.8, sharp and clear throughout, international film festival backdrop, 8K commercial quality.`,
      "2": `Half-body portrait of sophisticated Asian woman, wearing high-couture evening gown with elegant neckline, diamond jewelry sparkling under professional lighting, strong confident gaze directly at camera, red carpet professional lighting, medium close-up, 85mm f/2.0, 8K ultra-sharp, luxury magazine editorial style.`,
      "3": `Close-up portrait of iconic Asian actress, bold red lips, dramatic eye makeup with deep smoky shadow, flawless pale cool-toned skin, piercing confident gaze, sophisticated high-fashion makeup, soft directional studio lighting, 105mm f/1.4, commercial beauty photography, 8K resolution.`,
      "4": `Three-quarter profile of elegantly dressed Asian woman, sleek updo hairstyle showing neck and jaw line, luxurious evening gown shoulder detail, soft side lighting creating elegant shadows, minimal and clean background, 85mm f/1.8, fashion editorial style.`,
      "5": `Low angle shot looking up at confident Asian woman, full-length evening gown flowing downward, powerful confident posture and expression, dramatic lighting from above, conveying authority and star power, 50mm f/2.8, cinematic quality.`,
      "6": `Asian film star in elegant evening gown, standing on grand staircase or architectural setting, full environment visible, person centered, warm ambient lighting from venue, film noir aesthetic meets modern luxury, 35mm f/2.8, editorial storytelling style.`,
      "7": `Medium shot focusing on jewelry and gown detail, sparkling diamond necklace and earrings against elegant neckline, hands gracefully positioned showing ring detail, professional product-quality lighting on jewelry, 85mm macro-style, ultra-sharp details.`,
      "8": `Asian actress in evening wear turning to look back at camera, dramatic movement captured, gown trailing behind, professional studio or venue lighting, mysterious and alluring expression, 50mm f/2.0, motion elegance, editorial style.`
    },
    commonBase: "",
    negativeConstraints: `deformed face, plastic skin, over-smoothed, different person, wrong body proportions, ill-fitting gown, cheap fabric appearance, over-exposed, harsh shadows on face, watermark, signature`
  },
  "zhang_man_yu_02": {
    id: "zhang_man_yu_02",
    name: `都市现代·知性精英风`,
    styleName: `都市精英·现代知性·简约高级`,
    category: `张曼玉·现代知性`,
    description: `当代都市精英女性形象，现代商务知性`,
    format: "zm_v1",
    tags: [`自信独立`, `知性优雅`, `低调奢华`],
    shots: {
      "1": `Close-up portrait of elegant mature Asian woman, minimal makeup with natural dewy skin, wearing sleek dark blazer, soft natural side lighting, 85mm f/1.4, thoughtful intelligent gaze, calm confidence, clean light gray background, 8K commercial portrait.`,
      "2": `Half-body portrait, professional business setting, sophisticated Asian woman in tailored jacket, natural window lighting from left side, hands in relaxed professional position, 85mm f/1.8, neutral color palette, clean modern interior background.`,
      "3": `Side profile of intellectual Asian woman, minimal chic outfit, perfect posture, dramatic side lighting creating elegant contour, looking contemplatively to the side, 85mm f/2.0, monochromatic tones.`,
      "4": `Full body shot, urban modern setting, tailored outfit showing complete look, natural street light or interior light, confident relaxed posture, 50mm f/2.8, editorial city style.`,
      "5": `Medium shot, rare warm smile on elegant Asian woman, natural lighting, authentic moment, premium casual outfit, simple jewelry, 85mm f/1.8, warm neutral tones.`,
      "6": `Detail shot showing fabric texture and jewelry, high-quality material close-up, elegant hands and accessories, product-quality sharp lighting, 85mm f/2.0.`,
      "7": `Environmental portrait in modern art space or library, sophisticated woman reading or in contemplation, available ambient light, candid feel, 35mm f/2.8, documentary editorial style.`,
      "8": `Black and white portrait, timeless and classic, minimal makeup, clean lines, dramatic side lighting, strong contrast, film photography aesthetic, 85mm f/1.4, fine art portrait.`
    },
    commonBase: "",
    negativeConstraints: `over-stylized, too much makeup, flashy jewelry, cheap fabric, over-smoothed skin, plastic appearance, wrong proportions, watermark`
  },
  "zhang_man_yu_03": {
    id: "zhang_man_yu_03",
    name: `90年代港风·复古胶片情绪`,
    styleName: `90年代港风·胶片复古·慵懒高级`,
    category: `张曼玉·复古港风`,
    description: `香港黄金时代商业写真，90年代经典港风`,
    format: "zm_v1",
    tags: [`慵懒高级`, `冷艳妩媚`, `情绪感十足`],
    shots: {
      "1": `Close-up portrait of iconic Hong Kong actress from 1990s, loose wavy dark hair falling naturally over shoulders, matte rose-brown lips, subtle smoky eye liner, warm side backlight at 45 degrees creating rim light on hair, cool-toned fair skin with natural texture, film grain effect, vintage warm color grading, 85mm f/1.4, deep gray blurred background, retro Hong Kong glamour aesthetic.`,
      "2": `Medium close-up, woman sitting by wooden window frame, hand resting on frame, looking toward camera with languid gaze, soft warm backlight streaming through window, wearing black knit top with subtle shoulder detail, 50mm f/1.8, warm film tone, 1990s Hong Kong style.`,
      "3": `Side profile, loose waves falling forward, dramatic backlight creating hair glow, strong jawline and elegant neck visible, deep dark background, single light source, 85mm f/1.4, high contrast film look.`,
      "4": `Half-body shot, moody and atmospheric, dark fitted top showing collarbone and neckline, subtle jewelry catching light, layered soft warm lighting, 50mm f/2.0, film grain, warm tones.`,
      "5": `Over-the-shoulder look back at camera, wavy hair in motion, natural movement captured, strong warm side lighting, emotional and evocative expression, 85mm f/1.8, retro editorial.`,
      "6": `Full body shot in retro Hong Kong setting, urban street or vintage interior background, confident relaxed pose, natural street lighting or window light, 35mm f/2.8, warm film color.`,
      "7": `Shoulder-up portrait, direct sultry gaze at camera, perfect retro makeup, waves framing face, single warm side light, extremely shallow depth of field, 105mm f/1.2.`,
      "8": `Distance shot, Hong Kong urban environment, woman in stylish outfit amid city lights or old buildings, golden hour warm lighting, cinematic wide shot, 35mm f/2.8, nostalgic film aesthetic.`
    },
    commonBase: "",
    negativeConstraints: `modern digital look, overly bright, clinical lighting, over-smoothed, no grain texture, saturated colors, contemporary style, watermark`
  },
  "zhang_man_yu_04": {
    id: "zhang_man_yu_04",
    name: `芭蕾风·肢体优雅写真`,
    styleName: `芭蕾意境·肢体优雅·轻盈仙气`,
    category: `张曼玉·优雅艺术`,
    description: `舞蹈艺术写真，强调肢体线条与优雅姿态`,
    format: "zm_v1",
    tags: [`轻盈飘逸`, `古典优雅`, `仙气十足`],
    shots: {
      "1": `Full body ballet-inspired portrait of elegant Asian woman, wearing flowing white chiffon dress, graceful pose with arms extended, soft diffused studio lighting, all-white background, upswept hair showing slender neck, 50mm f/2.0, high-key lighting, dreamy aesthetic.`,
      "2": `Half-body shot, Asian woman in ethereal white dress, fabric billowing naturally, warm soft light from front-left, delicate features, natural makeup, 85mm f/1.8, luminous skin, soft glow.`,
      "3": `Close-up portrait showing delicate features, light natural makeup, pale rose lips, soft hair swept up elegantly, dreamy soft focus background, 105mm f/1.4, warm white tones.`,
      "4": `Captured mid-movement, white dress twirling, fabric creating beautiful circular motion, natural light from above, joyful elegant expression, 50mm f/2.8, motion blur on dress edges.`,
      "5": `Low angle looking up at graceful figure, long legs and flowing dress visible, bright studio light from behind creating halo effect, ethereal and goddess-like impression, 35mm f/2.0.`,
      "6": `Seated pose on white surface, knees drawn gracefully, dress arranged beautifully, soft natural light from window, thoughtful downward gaze, 85mm f/1.8.`,
      "7": `Back view showing elegant spine and shoulder blades, low-back dress or off-shoulder design, strong clean light from front, graceful posture, upswept hair, 85mm f/2.0.`,
      "8": `Wide shot, woman in white dress in flower garden or open space, small figure in large beautiful environment, natural golden light, impressionistic painterly feel, 35mm f/4.0.`
    },
    commonBase: "",
    negativeConstraints: `heavy makeup, dark clothing, harsh shadows, urban gritty feel, over-posed, stiff posture, watermark, low resolution`
  },
  "zhang_man_yu_05": {
    id: "zhang_man_yu_05",
    name: `冷艳高级·时尚杂志封面`,
    styleName: `冷艳高级·杂志封面·极致气场`,
    category: `张曼玉·高级杂志`,
    description: `国际顶级时尚杂志封面，极致高级感`,
    format: "zm_v1",
    tags: [`冷艳神秘`, `气场强大`, `无懈可击的高级感`],
    shots: {
      "1": `Extreme close-up, fierce and powerful expression, immaculate professional makeup with strong contoured features, cold yet magnetic gaze directly at camera, butterfly lighting creating perfect facial shadow, 105mm f/1.2, pure white or black background, high-fashion magazine cover quality, 8K ultra-sharp.`,
      "2": `Half-body fashion editorial shot, wearing strong-shouldered designer blazer, cool neutral tones, controlled dramatic lighting, commanding presence, no-apology confidence, 85mm f/1.8, high contrast, magazine editorial.`,
      "3": `Black and white fashion portrait, perfect skin texture, sculptural face, Rembrandt lighting, deep shadows and bright highlights, timeless and iconic quality, 105mm f/1.4, fine art photography.`,
      "4": `Slightly low angle, looking down at camera, power pose in structured designer outfit, overhead dramatic lighting, overwhelming presence and authority, 85mm f/2.0.`,
      "5": `Pure profile shot, sculptural jawline and nose, dramatic side lighting with deep shadow, slicked hair or clean updo, black background, single light source, 105mm f/1.4, fashion photography.`,
      "6": `Full body, strong fashion silhouette, designer outfit with dramatic shape, three-point lighting setup, confident powerful stance, 50mm f/2.8.`,
      "7": `Shoulders-up, mysterious expression, partially obscured by shadow or fabric, single dramatic directional light, deep and enigmatic mood, 85mm f/1.4.`,
      "8": `Distance shot, single figure in vast empty space, minimalist environment (white room/warehouse), isolated and powerful, 35mm f/4.0, conceptual fashion.`
    },
    commonBase: "",
    negativeConstraints: `sweet or cute expression, warm lighting, busy background, casual clothing, soft focus, romantic mood, watermark, ---, *by CC*`
  },
  "zhang_man_yu_06": {
    id: "zhang_man_yu_06",
    name: `慵懒露肩·性感写真风`,
    styleName: `慵懒性感·露肩写真·低调撩人`,
    category: `张曼玉·慵懒自然`,
    description: `成熟女性性感写真，低调而撩人`,
    format: "zm_v1",
    tags: [`慵懒妩媚`, `成熟性感`, `自信不刻意`],
    shots: {
      "1": `Close-up portrait, sultry and languid expression, off-shoulder or wide-neck top revealing collarbone, warm side backlight accentuating shoulder line, deep smoky eye, red or mauve lips, messy waves framing face, 85mm f/1.4, warm dark background, intimate mood.`,
      "2": `Medium shot emphasizing collarbone and shoulder line, silk or satin top slipping slightly off shoulder, warm directional lighting from side, head tilted with languid expression, 85mm f/1.8.`,
      "3": `Over-the-shoulder look, bare shoulder visible, deep meaningful gaze back at camera, dramatic warm backlight, hair falling loose and natural, 85mm f/1.4.`,
      "4": `Half-body lying or leaning pose, relaxed body language, intimate setting, warm ambient lighting, 50mm f/1.8, soft warm tones.`,
      "5": `Extreme close-up on eyes and upper face, dramatic eye makeup, seductive gaze, soft defocused background, 105mm f/1.2, rich texture.`,
      "6": `Full body on bed or sofa, relaxed elegant pose, off-shoulder outfit, natural body curves, warm window light or lamp light, 35mm f/2.0, intimate editorial.`,
      "7": `Close-up of neckline, shoulder, and collarbone area, jewelry detail against smooth skin, warm dramatic lighting, macro-style, sensual detail.`,
      "8": `Woman by window, warm light flooding in, off-shoulder or loose top, dreamy and romantic mood, 50mm f/1.8, warm morning light feel.`
    },
    commonBase: "",
    negativeConstraints: `stiff pose, formal attire, cold lighting, corporate feel, over-dressed, inappropriate exposure, watermark, ---, *by CC*`
  },
  "zhang_man_yu_07": {
    id: "zhang_man_yu_07",
    name: `纯净白色·清新系`,
    styleName: `纯净白色·清新系`,
    category: `张曼玉·清新纯净`,
    description: `轻盈、干净、少女感中透着成熟的优雅`,
    format: "zm_v2",
    tags: [`纯净白色`, `清新淡雅`, `减法美学`],
    shots: {
      "1": `portrait close-up, pure white chiffon top, soft diffused high-key light, no-makeup look with glossy skin, nude pink lips, 85mm f/1.8, white seamless background, ultra clean and pure atmosphere, delicate skin texture, serene expression`,
      "2": `extreme close-up on eyes, soft eyelashes, natural brow arch, sheer light from front-left, skin glowing like porcelain, 100mm macro portrait, white background, ethereal and calm, no heavy eye makeup`,
      "3": `half-body portrait, white linen off-shoulder top, pearl stud earrings, soft wrap light, 50mm f/2.0, gentle shadow transition, calm and elegant posture, subject looking slightly off-camera, white background`,
      "4": `side profile portrait, straight black hair falling softly, thin silver necklace, high-key side light outlining facial contour, 85mm f/2.0, white background, minimalist and sculptural composition`,
      "5": `subject near sheer white curtain, natural daylight diffusing through, white silk slip dress, gentle breeze effect on fabric, 50mm f/1.8, soft warm-white tone, dreamy and light atmosphere`,
      "6": `low-angle half-body shot, white wide-shoulder blouse, chin slightly lifted, confident yet delicate posture, even soft front lighting, 35mm f/2.8, clean white-gray background, fresh and radiant`,
      "7": `full body seated portrait, white cotton maxi dress, bare feet or simple white flats, natural posture with arms relaxed, soft studio lighting from above-left, 35mm f/2.8, white floor and background, minimal and airy`,
      "8": `portrait with white gardenia flowers, subject holding flowers near chin, soft front light with fine bloom highlight, 85mm f/1.8, very low saturation, ivory-white tone, pure and fragrant atmosphere`
    },
    commonBase: "",
    negativeConstraints: ""
  },
  "zhang_man_yu_08": {
    id: "zhang_man_yu_08",
    name: `艺术气质·文艺写真风`,
    styleName: `艺术气质·文艺写真风`,
    category: `张曼玉·文艺气质`,
    description: `内敛深沉，若有所思，艺术家的冷静与热情并存`,
    format: "zm_v2",
    tags: [`文艺气质`, `知识分子美学`, `人文纪实质感`],
    shots: {
      "1": `close-up portrait, single window light from left, defined cheekbone shadow, natural bun with loose strands, nude brown lips, earth-tone knit top, 85mm f/2.0, film grain, contemplative expression, muted warm tones`,
      "2": `half-body portrait in front of wooden bookshelf, loose linen cream shirt, round glasses, holding a book, Rembrandt window lighting, 50mm f/2.8, intellectual atmosphere, muted color palette`,
      "3": `extreme eye contact close-up, deep smoky brown eye makeup, natural thick brows, warm side light, 85mm f/1.8, artistic melancholy, film texture, skin natural pores visible`,
      "4": `side profile at vintage window, low ponytail with loose strands, oversized grey coat, cold outdoor vs warm interior light contrast, 50mm f/2.0, poetic literary mood`,
      "5": `subject seated at antique wooden desk, reading or writing, cream high-neck sweater, warm lamp side light, 50mm f/2.0, shallow depth of field, cozy intellectual atmosphere, film grain`,
      "6": `full body in vintage library, dark green knit dress, simple leather shoes, warm diffused light, 35mm f/2.8, layered bookshelves background, dignified and thoughtful posture`,
      "7": `half-body at cafe table, warm side light, exposed brick wall, holding coffee cup, loose wavy hair, checked blazer, 50mm f/2.0, autumn tones, candid artistic feel`,
      "8": `full body walking through old building corridor, linen trousers and oversized knit, natural overhead light, 35mm f/2.8, film-inspired warm grain, documentary humanist style`
    },
    commonBase: `8K超清，人文纪实质感，单侧自然窗光，文艺大地色调，自然妆容，保留用户面部原始特征，肢体比例正常无变形，整体氛围安静内省`,
    negativeConstraints: `heavy glamour makeup, bold red lips, high-key bright background, fashion gloss, distorted face, deformed hands, extra limbs, blurry, low quality, celebrity face substitution, overly polished skin`
  },
  "zhang_man_yu_09": {
    id: "zhang_man_yu_09",
    name: `成熟知性·中期风格`,
    styleName: `成熟知性·中期风格`,
    category: `张曼玉·成熟知性`,
    description: `自信从容，历经岁月沉淀的气场，不需证明的高级感`,
    format: "zm_v2",
    tags: [`成熟优雅`, `女性力量`, `国际化都市感`],
    shots: {
      "1": `close-up portrait, butterfly lighting, defined cheekbones and jawline, sleek bob haircut, matte rose lips, sharp defined brows, 85mm f/2.0, dark neutral background, commanding and confident expression`,
      "2": `half-body portrait in black tailored blazer, silk white blouse underneath, minimal gold earrings, even professional lighting, 85mm f/2.0, clean dark gray background, mature elegant atmosphere`,
      "3": `extreme close-up, sharp eyeliner, dark brown smoky eye, defined brow arch, flawless matte skin, 100mm f/2.0, cool-toned lighting, strong silent power in gaze`,
      "4": `full body against modern glass building exterior, wine-red fitted coat, structured handbag, natural urban daylight, 35mm f/2.8, city architecture background, sophisticated and polished`,
      "5": `half-body seated portrait, crossed arms, camel turtleneck sweater, structured silver necklace, medium-hard studio light from side, 85mm f/2.0, deep gray background, self-assured posture`,
      "6": `three-quarter side portrait, sleek center-parted long hair, deep wine matte lips, 135mm f/2.8 compression, minimal background, strong facial contour emphasized by side light`,
      "7": `full body walking in modern hotel corridor or art gallery, tailored pantsuit in charcoal gray, confident stride, ambient architectural lighting, 35mm f/2.8, cinematic and purposeful energy`,
      "8": `half-body in front of concrete wall, black mock-neck top, statement oversized earrings, industrial side light, 85mm f/2.0, raw texture background contrasts polished subject, editorial fashion feel`
    },
    commonBase: `8K超清，商业人像质感，蝴蝶光或环形灯，成熟优雅中性色调，精致妆容，保留用户面部原始特征，肢体比例正常无变形，整体氛围自信从容`,
    negativeConstraints: `girlish cute style, pastel colors, heavy film grain, distorted face, deformed hands, extra limbs, blurry, low quality, celebrity face substitution, overly softened skin, costume or cosplay elements`
  },
  "zhang_man_yu_10": {
    id: "zhang_man_yu_10",
    name: `花样年华·红色旗袍`,
    styleName: `花样年华·红色旗袍`,
    category: `张曼玉·花样年华`,
    description: `压抑的热烈，克制中涌动的情欲与哀愁，极度内敛的东方女性之美`,
    format: "zm_v2",
    tags: [`民国上海`, `旗袍文化`, `王家卫电影美学`],
    shots: {
      "1": `close-up portrait, dark red satin qipao collar detail, 1960s chignon updo, deep red matte lips, classic cat eyeliner, porcelain pale skin, warm amber backlight from behind, 85mm f/1.8, heavy film grain, melancholic expression`,
      "2": `full body in dimly lit narrow corridor, deep red floral qipao with side slit, amber lamplight casting long shadows, 50mm f/1.4, strong film grain, symmetrical corridor composition, silent longing atmosphere`,
      "3": `extreme macro close-up on lips and chin only, deep matte crimson lips, porcelain skin, soft amber light, 100mm macro, fine skin texture, sensual and restrained beauty`,
      "4": `side profile, subject leaning against worn plaster wall, dark red qipao silhouette, warm back-rim light highlighting hair and shoulder curve, 85mm f/2.0, moody low-key, vintage wallpaper texture`,
      "5": `three-quarter body on vintage spiral staircase, dark red silk qipao with embroidered pattern, pearl earrings, warm tungsten light from above, 50mm f/1.8, film noir mood, architectural shadows`,
      "6": `half-body by window with lattice shadow pattern falling on face and qipao, warm evening light, 85mm f/1.8, graphic shadow pattern creates visual tension, melancholic gaze outward`,
      "7": `close-up of hands holding a teacup or resting on railing, qipao sleeve edge visible, jade ring detail, warm side light, 100mm f/2.8, elegant and wistful, story-rich detail shot`,
      "8": `full body walking away then glancing back over shoulder, dark red qipao showing back and side slit, dim corridor amber light, 35mm f/2.0, iconic In the Mood for Love composition, lingering emotional weight`
    },
    commonBase: `8K超清，王家卫电影美学，昏黄暖调逆光，红色旗袍，复古盘髻，深红哑光唇，保留用户面部原始特征，肢体比例正常无变形，整体氛围压抑深情`,
    negativeConstraints: `modern clothing, bright white lighting, heavy digital retouching, clean background, no film grain, cute or bright color palette, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution`
  },
  "zhang_man_yu_11": {
    id: "zhang_man_yu_11",
    name: `花样年华·蓝绿旗袍`,
    styleName: `花样年华·蓝绿旗袍`,
    category: `张曼玉·花样年华`,
    description: `比红旗袍更冷艳，带有疏离感与神秘感，克制中的优雅`,
    format: "zm_v2",
    tags: [`民国上海`, `孔雀蓝旗袍`, `王家卫冷色系电影美学`],
    shots: {
      "1": `close-up portrait, peacock blue-green qipao collar, 1960s updo hairstyle, cool matte rose lips, thin cat eyeliner, porcelain cool-toned skin, blue moonlight side light, 85mm f/1.8, film grain, serene and distant expression`,
      "2": `full body in narrow rain-soaked corridor at night, teal qipao with embroidered pattern, mixed warm amber and cool blue lighting, 50mm f/1.4, strong film grain, wet floor reflection, solitary atmospheric`,
      "3": `half-body portrait, warm amber lamp on one side, cool moonlight blue on other, blue-green silk qipao, face split between warm and cool tones, 85mm f/2.0, deep moody contrast, contemplative gaze`,
      "4": `subject framed against rainy night window, blue-tinted exterior, peacock blue qipao from inside warm but face lit by blue reflection, 50mm f/1.8, layered depth of field, romantic melancholy`,
      "5": `side profile, cool blue side light carving out facial contour, silver jade earring detail, glossy qipao shoulder curve, 135mm compression, dark blue-black background, sculptural and mysterious`,
      "6": `three-quarter body on spiral staircase, teal green qipao, cool overhead light casting blue shadows, 50mm f/1.8, high contrast between qipao color and dark surroundings, film noir with Chinese aesthetic`,
      "7": `subject reflected in antique mirror, both real and reflection visible, blue-green qipao, dim warm lamp from side, 50mm f/2.0, dreamlike layered composition, time-suspended atmosphere`,
      "8": `full body from behind walking in rain, peacock blue qipao showing side slit, wet cobblestone street reflecting neon traces, 35mm f/2.0, blurred street lights as bokeh, iconic departure image`
    },
    commonBase: `8K超清，王家卫电影美学冷色版，蓝调月光与暖黄灯光对比，蓝绿旗袍，复古盘髻，冷调玫瑰唇，保留用户面部原始特征，肢体比例正常无变形，整体氛围冷艳神秘`,
    negativeConstraints: `bright daylight, cheerful colors, warm red dominant, heavy digital retouching, clean modern background, no film grain, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution`
  },
  "zhang_man_yu_12": {
    id: "zhang_man_yu_12",
    name: `花样年华·黑色旗袍`,
    styleName: `花样年华·黑色旗袍`,
    category: `张曼玉·花样年华`,
    description: `最克制最沉静的一款，黑色旗袍承载最深的悲与美，如送别`,
    format: "zm_v2",
    tags: [`终极东方优雅`, `黑旗袍`, `极致压抑美学`],
    shots: {
      "1": `extreme close-up portrait, narrow beam of warm light illuminating face from side, black velvet qipao collar barely visible, smooth tight chignon, dark red-black matte lips, sharp black eyeliner, 85mm f/1.4, near-black background, extreme low-key, solemn and beautiful`,
      "2": `full body in pitch-black surroundings, single overhead light beam on subject, black satin qipao with subtle gold embroidery, pearl earring glinting, 50mm f/1.4, extreme contrast, statuesque and still posture`,
      "3": `intense close-up eye contact, sharp defined black eyeliner, dark iris, no colored eye shadow, warm rim light on eyelids, 85mm f/1.8, high contrast black background, unwavering powerful gaze`,
      "4": `side silhouette portrait, black qipao curve from neck to waist highlighted by narrow side light, face partially in shadow, smooth chignon visible, 85mm f/2.0, black background, architectural body line`,
      "5": `close-up of black qipao fabric with gold embroidery detail, hand resting on fabric, single soft light raking across texture, 100mm macro, tactile and luxurious material quality`,
      "6": `full body at end of dark corridor, small distant light source ahead, black qipao silhouette from behind, smooth hair bun, 35mm f/2.0, vast darkness surrounding subject, departing or arriving ambiguity`,
      "7": `half-body seated, black qipao with straight back posture, hands folded in lap, single candle-warm spotlight, 85mm f/1.8, deep shadow on lower half, contemplative downward gaze, dark background`,
      "8": `three-quarter turn, black qipao showing back embroidery detail, glancing back over shoulder, warm rim light on profile and shoulder, 85mm f/1.8, near-black background, closing scene energy, heartbreaking elegance`
    },
    commonBase: `8K超清，极致low-key王家卫美学，单点光源烛光感，黑色旗袍，光滑盘髻，黑红哑光唇，保留用户面部原始特征，肢体比例正常无变形，整体氛围庄重悲美`,
    negativeConstraints: `bright cheerful colors, high-key lighting, colorful accessories, casual clothing, film grain (optional minimal only), distorted face, deformed hands, extra limbs, blurry, celebrity face substitution, gaudy decoration`
  },
  "zhang_man_yu_13": {
    id: "zhang_man_yu_13",
    name: `Vogue China·极简现代风`,
    styleName: `Vogue China·极简现代风`,
    category: `张曼玉·现代时尚`,
    description: `冷静、自信、超越年龄的当代感，不迎合的高级`,
    format: "zm_v2",
    tags: [`国际时尚大刊`, `极简主义`, `当代女性力量美学`],
    shots: {
      "1": `magazine cover close-up, slicked-back wet hair, bold red lips only, bare clean skin, strong front-left hard studio light, sharp facial shadow, 85mm f/2.8, pure white background, Vogue China editorial power`,
      "2": `full body, oversized structured black coat with strong shoulders, no accessories, slicked hair, bare lips, hard side light, pure white background, 35mm f/2.8, fashion editorial power pose, graphic composition`,
      "3": `close-up, extreme smoky eye with bare nude lips, skin-tight black turtleneck, slicked hair behind ear, hard directional light from above-side, 85mm f/2.0, black background, graphic strong beauty`,
      "4": `full body against white brutalist concrete wall, architectural geometric shadow patterns from window, white structured suit, 35mm f/2.8, midday hard outdoor light, cold and commanding fashion pose`,
      "5": `sharp side profile portrait, rim light only, face partially in deep shadow, white or black background, 85mm f/2.0, high contrast, architectural facial geometry, fashion sculpture feel`,
      "6": `half-body in single vivid color (electric blue or scarlet red) structured blazer, no jewelry, slicked hair, nude lips, seamless white background, fashion strobe light front-soft, bold color punch`,
      "7": `full body on white seamless floor, white outfit head to toe, white background, differentiated by shadow and form only, 35mm f/4.0, fashion geometry, subject is a human sculpture`,
      "8": `close-up tilted head showing oversized geometric gold earring, bare minimum makeup, hard side light emphasizing jewelry and cheekbone, 85mm f/2.0, white background, object-meets-portrait editorial`
    },
    commonBase: `8K超清，Vogue级商业大片质感，硬光雕塑感打光，极简廓形服饰，单一强调妆容，保留用户面部原始特征，肢体比例正常无变形，整体氛围超然自信`,
    negativeConstraints: `busy patterns, multiple colors, romantic or soft mood, warm cozy atmosphere, heavy film grain, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution, over-retouched doll skin`
  },
  "zhang_man_yu_14": {
    id: "zhang_man_yu_14",
    name: `Harper's Bazaar·封面大片风`,
    styleName: `Harper's Bazaar·封面大片风`,
    category: `张曼玉·封面大片`,
    description: `华丽而有故事感，比Vogue更具温度与叙事性，美得有情节`,
    format: "zm_v2",
    tags: [`高级时尚大刊`, `华丽精致`, `叙事性时装大片`],
    shots: {
      "1": `magazine cover portrait, butterfly light, full glamour makeup, voluminous soft waves, glossy red lips, pearl and diamond earrings, 85mm f/2.0, warm golden background, Harper's Bazaar cover composition, confident and alluring`,
      "2": `full body in floor-length couture gown with intricate embroidery, grand ballroom setting, warm chandelier light, 35mm f/2.8, subject center frame, regal and luminous posture`,
      "3": `close-up portrait emphasizing statement necklace and earrings against bare decolletage, elegant updo, warm rim light highlighting jewelry, 85mm f/2.8, dark velvet background, luxury product-meets-portrait`,
      "4": `half-body in ornate European interior, gilded chair and drapes background, wine-red velvet dress, layered pearl jewelry, dramatic warm-cool light contrast, 50mm f/2.0, editorial storytelling mood`,
      "5": `full body in silk evening gown, strong warm backlight creating halo effect, grand architectural interior, 35mm f/2.8, subject walking toward camera, high drama and movement energy`,
      "6": `extreme close-up on eyes only, impeccable eye makeup with thick false lashes and precise liner, arched brow, golden shadow accent, warm side light, 100mm macro, luxury beauty editorial`,
      "7": `elegant seated portrait in velvet armchair, couture jacket with embellished collar, layered necklaces, one hand gracefully posed, warm ambient light, 50mm f/2.0, rich jewel-toned background`,
      "8": `full body against floor-to-ceiling velvet drapes, champagne or gold gown, wind-effect on fabric, warm golden backlight, 35mm f/2.0, theatrical and majestic atmosphere, Harper's Bazaar fantasy spread`
    },
    commonBase: `8K超清，Harper's Bazaar封面级大片质感，精致全妆，华丽礼服或高定套装，专业蝴蝶光打光，保留用户面部原始特征，肢体比例正常无变形，整体氛围华丽从容`,
    negativeConstraints: `casual clothing, minimal makeup, harsh industrial setting, cold blue tones, heavy film grain, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution, flat unlit background`
  },
  "zhang_man_yu_15": {
    id: "zhang_man_yu_15",
    name: `阮玲玉·民国复古造型`,
    styleName: `阮玲玉·民国复古造型`,
    category: `张曼玉·民国复古`,
    description: `沉郁而诗意，旧时代女性的悲情与光芒，如《阮玲玉》电影质感`,
    format: "zm_v2",
    tags: [`民国上海滩`, `1930年代老电影美学`, `黑白年代感`],
    shots: {
      "1": `close-up portrait in monochrome, 1930s finger wave hairstyle, thin arched brows, red cupid's bow lips, round blush marks on cheeks, period studio portrait light, 85mm f/2.0, high contrast black-and-white, film scratch vignette, silent film era beauty`,
      "2": `half-body in 1930s style qipao, jade bracelet, black-and-white, single side studio light, blown highlight on cheek, 85mm f/2.0, period photo studio backdrop, graceful and melancholic posture`,
      "3": `subject standing at shikumen alley entrance, 1930s qipao, natural daylight, sepia tone, worn stone wall texture, 50mm f/2.8, period street photography feel, melancholic and poetic`,
      "4": `close-up of hands holding antique pocket watch, qipao sleeve visible, jade ring, soft warm side light, sepia or low-saturation color, rich material detail, nostalgic and wistful`,
      "5": `full body in 1930s photo studio, painted European landscape backdrop, standing formal pose, 1930s qipao, finger wave hair, 35mm f/2.8, high contrast black-and-white with vignette, calendar girl composition`,
      "6": `half-body portrait in vintage Shanghai calendar girl style, colorful but desaturated 1930s qipao, graphic composition with decorative border feel, warm period colors, 50mm f/2.0, retro illustration-meets-photography aesthetic`,
      "7": `subject by window with lattice shadow on face, black-and-white, dramatic high contrast, 1930s qipao, downward gaze, 85mm f/1.8, period drama and melancholy`,
      "8": `full body turning corner in old Shanghai alley, wet cobblestone ground, 1930s clothing, sepia tone, ambient alley light, 35mm f/2.8, cinematic period realism, like a frame from a 1930s film`
    },
    commonBase: `8K超清，1930年代旧式摄影美学，黑白或极低饱和度，民国旗袍，油光波浪发，弓形红唇，保留用户面部原始特征，肢体比例正常无变形，整体氛围沉郁悲美`,
    negativeConstraints: `modern makeup, contemporary clothing, digital retouching, bright saturated colors, clean high-tech background, no grain or texture, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution`
  },
  "zhang_man_yu_16": {
    id: "zhang_man_yu_16",
    name: `戛纳红毯·华丽礼服风（二）`,
    styleName: `戛纳红毯·华丽礼服风（二）`,
    category: `张曼玉·红毯礼服`,
    description: `隆重而自然，不刻意的顶级明星气场，礼服与人融为一体`,
    format: "zm_v2",
    tags: [`国际电影节红毯`, `欧洲奢华`, `闪光灯下的从容`],
    shots: {
      "1": `full body on red carpet, floor-length gold crystal-embellished gown with train, elaborate updo, diamond necklace, front paparazzi flash lighting, 35mm f/2.8, step-and-repeat logo backdrop, majestic and luminous`,
      "2": `half-body close up, deep smoky eye with dramatic lashes, highlighted cheekbones, nude rose lips, pearl updo, jewel-toned gown shoulder detail, bright even red carpet lighting, 85mm f/2.0, star power`,
      "3": `full body glancing back over shoulder, sapphire blue couture gown flowing to ground, chandelier earrings, outdoor event spotlights, 35mm f/2.8, night sky background with bokeh lights, iconic film star moment`,
      "4": `low angle showing gown skirt detail, crystal embroidery and tulle layers, subject walking up steps, high heels and gown hem, evening event lighting, 35mm f/2.8, cinematic grandeur`,
      "5": `full body descending grand staircase at night, emerald green silk gown, strong spotlights from below creating dramatic uplighting, 35mm f/2.8, architectural background, theatrical and commanding presence`,
      "6": `close-up of neck and décolleté, spectacular diamond or emerald necklace against bare skin, gown neckline visible, warm gem-light reflection, 85mm f/2.0, elegant and opulent`,
      "7": `half-body portrait, wine-red satin gown, ruby earrings and matching lips (exception: coordinated red-on-red), strong from-above event lighting, 85mm f/2.8, clean dark background suggesting night sky, film festival poster energy`,
      "8": `full body surrounded by soft event lights and bokeh, champagne sequin gown catching every light source, relaxed poised stance, ambient night photography, 35mm f/2.0, dream-like luminous quality`
    },
    commonBase: `8K超清，戛纳红毯级大片质感，闪光灯正面强光，华丽礼服，全妆高光，保留用户面部原始特征，肢体比例正常无变形，整体氛围隆重从容`,
    negativeConstraints: `casual outfit, daytime setting, flat lighting, no jewelry, muted colors, distorted face, deformed hands or feet, extra limbs, blurry, celebrity face substitution, costume or theatrical makeup`
  },
  "zhang_man_yu_17": {
    id: "zhang_man_yu_17",
    name: `Chanel广告·法式极简风`,
    styleName: `Chanel广告·法式极简风`,
    category: `张曼玉·法式极简`,
    description: `法国式的随性不费力之美，奢华而不张扬，简单到极致即是高级`,
    format: "zm_v2",
    tags: [`香奈儿品牌美学`, `法式优雅`, `极简奢华`],
    shots: {
      "1": `half-body portrait, classic Chanel black tweed jacket with gold buttons, layered pearl necklaces, camellia brooch, French window light from left, 85mm f/2.0, warm white background, effortless Parisian elegance, classic red lips`,
      "2": `full body in Parisian apartment, white walls and herringbone wooden floor, black-white tweed set, black chain bag, natural window light, 35mm f/2.8, graceful and understated luxury lifestyle`,
      "3": `close-up of neck and pearl necklace detail, bare décolleté with Chanel jacket lapel, natural daylight, 85mm f/2.8, soft focus on layered pearls, timeless and feminine`,
      "4": `subject silhouetted against tall Parisian window, LBD (little black dress) silhouette, French bun hairstyle, afternoon backlight, 85mm f/1.8, romantic and mysterious French light`,
      "5": `half-body portrait holding a white camellia, Chanel tweed in cream and black, bare lips, soft front window light, 50mm f/2.0, delicate and feminine French girl aesthetic`,
      "6": `seated casually on French antique sofa, one leg crossed, black-white Chanel set, pearls, slightly disheveled low bun, warm side lamp light, 50mm f/2.0, candid magazine moment`,
      "7": `full body on Paris street (blurred background), classic Chanel beige jacket, black trousers, loafers, chain bag, soft overcast daylight, 35mm f/2.8, French street style with couture touch`,
      "8": `extreme close-up face and neck, bare luminous skin, single drop of perfume on collarbone, red lips only makeup, 85mm f/1.8, warm back light creating skin glow, Chanel No.5 advertisement aesthetic`
    },
    commonBase: `8K超清，Chanel广告大片质感，法式自然窗光，经典黑白配色，珍珠配饰，无妆感或经典红唇，保留用户面部原始特征，肢体比例正常无变形，整体氛围随性高级`,
    negativeConstraints: `colorful non-Chanel palette, heavy jewelry overkill, busy patterns, harsh industrial setting, cold blue tones, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution, cheap-looking fabrics`
  },
  "zhang_man_yu_18": {
    id: "zhang_man_yu_18",
    name: `90年代初·甜美邻家风`,
    styleName: `90年代初·甜美邻家风`,
    category: `张曼玉·甜美邻家`,
    description: `青涩、甜美、无辜，刚出道的明星气质中透着少女纯真`,
    format: "zm_v2",
    tags: [`1990年代初港台甜美风`, `邻家少女`, `青春偶像初期形象`],
    shots: {
      "1": `close-up portrait with bright smile, big permed wave hair, large round coral blush circles, glossy orange-pink lips, bright blue eyeshadow accent, warm outdoor natural light, 50mm f/2.8, warm Kodak film color, 90s idol sweetness`,
      "2": `half-body in pastel floral sundress, side-swept bangs with big waves, white background or park greenery, even bright daylight, 50mm f/2.8, high saturation warm tones, fresh and cheerful`,
      "3": `half-body in blue-white striped cotton tee, high-waist light-wash jeans, simple stud earrings, casual outdoor setting, bright mid-day light, 50mm f/4.0, 90s casual magazine spread energy`,
      "4": `full body at seaside or harbor, white cotton dress, wind-blown voluminous curly hair, bright sunny day, 35mm f/2.8, warm film color shift, sea and blue sky background, carefree and luminous`,
      "5": `dynamic action shot, subject twirling or laughing mid-turn, colorful pleated skirt, hair flying, bright park background, 50mm f/4.0, motion-frozen moment, 90s idol promotional photo energy`,
      "6": `full body leaning against school gate or white wall, simple pastel top and shorts, one hand in hair, bright outdoor light, 35mm f/2.8, clean urban background with greenery, youthful and innocent`,
      "7": `low angle shot looking up, subject smiling down at camera, big wavy hair framing face, blue sky background, bright overhead sun, 35mm f/2.8, 90s cheerful energy, summer idol shoot`,
      "8": `half-body in studio with flat even warm light, white or pastel backdrop, coral-pink outfit, full 90s sweet makeup, direct camera gaze with soft smile, 50mm f/2.8, even brightness, idol photo card style`
    },
    commonBase: `8K超清，90年代初港台青春质感，明亮自然光，暖色胶片偏色，甜美妆容大腮红，棉质休闲服饰，保留用户面部原始特征，肢体比例正常无变形，整体氛围青春活泼`,
    negativeConstraints: `dark moody atmosphere, muted colors, heavy dramatic makeup, sophisticated mature style, architectural background, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution`
  },
  "zhang_man_yu_19": {
    id: "zhang_man_yu_19",
    name: `警察故事时期·清纯清新风`,
    styleName: `警察故事时期·清纯清新风`,
    category: `张曼玉·清纯清新`,
    description: `纯真、清爽、带一点俏皮，是张曼玉最无邪时期的美`,
    format: "zm_v2",
    tags: [`1980年代末港片`, `清纯爱情喜剧`, `阳光少女感`],
    shots: {
      "1": `close-up portrait, natural minimal makeup, clear dewy skin, simple fluffy 80s hair, light pink glossy lips, bright even white light, 85mm f/2.8, cool-toned Fuji film color, pure and bright-eyed expression`,
      "2": `half-body candid-style portrait on Hong Kong street, sky-blue round-neck sweater, natural windswept hair, soft daylight, 50mm f/2.8, cool-toned street photography feel, spontaneous and charming`,
      "3": `full body at bus stop or MTR station, white shirt and light-wash jeans, simple ponytail, urban natural light, 35mm f/2.8, city life background, clean and fresh urban girl`,
      "4": `three-quarter body looking back over shoulder with bright playful smile, mint green top, simple small earrings, outdoor bright light, 50mm f/2.8, 80s HK rom-com energy, lighthearted and natural`,
      "5": `half-body near glass window, soft indoor daylight, cream or white knit sweater, simple stud earrings, 85mm f/2.0, cool-clean light, clear background, gentle genuine smile, girl-next-door charm`,
      "6": `full body in school corridor or playground, simple school-adjacent outfit (pastel dress or sweater skirt combo), natural hair, bright even daylight, 35mm f/4.0, clean campus background, youthful and innocent`,
      "7": `half-body, subject looking down reading with slight smile, soft window light on face, simple cool-tone top, natural hair falling forward, 85mm f/2.0, candid quiet moment, honest and unposed`,
      "8": `subject looking up into sun, squinting with natural smile, bright backlight creating rim around hair, light summer dress, outdoor park or rooftop, 50mm f/2.0, overexposed highlights, carefree youthful energy`
    },
    commonBase: `8K超清，80年代末港片清纯质感，明亮日光感，清冷色调，极简妆容，简约棉质服饰，保留用户面部原始特征，肢体比例正常无变形，整体氛围清纯活泼`,
    negativeConstraints: `heavy makeup, dark moody lighting, elaborate hairstyle, mature sophisticated style, film grain (very minimal ok), distorted face, deformed hands, extra limbs, blurry, celebrity face substitution, revealing clothing`
  },
  "zhang_man_yu_20": {
    id: "zhang_man_yu_20",
    name: `东方意境·水墨留白风`,
    styleName: `东方意境·水墨留白风`,
    category: `张曼玉·东方意境`,
    description: `宁静如湖，虚实相生，人与自然的哲学对话，不说话的深远`,
    format: "zm_v2",
    tags: [`中国水墨美学`, `诗意留白`, `东方禅意写真`],
    shots: {
      "1": `close-up portrait, ink-wash desaturated tones, pale luminous skin, willow-leaf brows, minimal eye makeup, light pink lips, classical bun with jade hairpin, cool soft diffused light, 85mm f/2.0, negative space white background, Chinese painting beauty`,
      "2": `full body in flowing white silk hanfu, misty lotus pond background, fabric billowing softly, cool overcast light, 85mm f/1.8, heavy background blur creating ink-wash depth, ethereal and timeless`,
      "3": `half-body portrait in bamboo grove, pale green-gray light filtering through bamboo, gray-white linen Chinese robe, simple bamboo hairpin, 85mm f/2.0, soft dappled cool light, monk-like serenity`,
      "4": `full body standing in Jiangnan courtyard, white plaster wall with black tile roof in background, ink-wash blue qipao or silk robe, one hand touching wall, cool even light, 35mm f/2.8, architecture and human in harmony`,
      "5": `subject occupying only right third of frame, rest pure white negative space, holding single lotus flower, minimal ink-wash style clothing, cool soft light, 85mm f/2.0, painting-within-photography composition`,
      "6": `full body on stone bridge over misty mountain stream, flowing gray silk dress, mist obscuring lower half, 50mm f/2.0, cool misty atmosphere, figure like a brushstroke in a landscape painting`,
      "7": `half-body seated reading a classical scroll, hanfu sleeve falling gracefully, warm stone table, cool ambient studio light, 85mm f/2.0, scholarly and serene, ink-wash monochrome palette`,
      "8": `full body in light rain, white translucent silk dress absorbing rain, hair slightly damp but poised, cool gray overcast light, 35mm f/2.0, wet stone path reflection, poetic and unreachable beauty, ultimate ink-wash portrait`
    },
    commonBase: `8K超清，中国水墨美学，极柔散射冷白光，大面积留白构图，汉服或中式素衣，极淡东方妆，保留用户面部原始特征，肢体比例正常无变形，整体氛围禅意静默`,
    negativeConstraints: `bright saturated colors, modern Western clothing, dramatic studio flash, warm orange tones, heavy glamour makeup, busy background, distorted face, deformed hands, extra limbs, blurry, celebrity face substitution`
  }
};
